version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4-rc
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - 27020:27017
    volumes:
      - ./data:/data/db
    networks:
      - app
    

  server:
    container_name: express
    image: express-server
    build: ./server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
    depends_on:
      - mongodb
  
  react-ui:
    container_name: react-ui
    image: node-react
    build: ./react-ui
    volumes:
      - ./react-ui:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - "3000:3000"
    stdin_open: true
    networks:
      - app

networks:
  app:
    driver: bridge
