version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - 27020:27017
    volumes:
      - ./data:/data/db
    networks:
      - app
    

  server:
    container_name: express
    image: express-server
    build: ./server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
    depends_on:
      - mongodb

networks:
  app:
    driver: bridge
